### ISSUE TITLE
New version of HA is causing problems with broadcast reception...

### ISSUE THREAD

**Issue by BluThunder2k** [siku2/hass-weatherlink#23]
Hi,

Add on has been working perfectly....

Till today, version 2202.7.0 of Home Assistant got installed.

If I have broadcast enabled, no data arrives, and my log fills with this:

RuntimeError: dictionary changed size during iteration
2022-07-06 17:04:39 ERROR (MainThread) [custom_components.weatherlink] failed to read broadcast
Traceback (most recent call last):
  File "/config/custom_components/weatherlink/__init__.py", line 132, in __broadcast_loop
    await self.__broadcast_loop_once(broadcast)
  File "/config/custom_components/weatherlink/__init__.py", line 120, in __broadcast_loop_once
    for update_callback in self._listeners:
RuntimeError: dictionary changed size during iteration
2022-07-06 17:04:42 ERROR (MainThread) [custom_components.weatherlink] failed to read broadcast
Traceback (most recent call last):
  File "/config/custom_components/weatherlink/__init__.py", line 132, in __broadcast_loop
    await self.__broadcast_loop_once(broadcast)
  File "/config/custom_components/weatherlink/__init__.py", line 120, in __broadcast_loop_once
    for update_callback in self._listeners:
RuntimeError: dictionary changed size during iteration

Disable broadcast and go to say 5 seconds, it continues to work.

Dave

**Comment by BluThunder2k** [comment]
Thanks!!

**Comment by siku2** [comment]
Just released version 0.5.3, which should contain a fix for this bug. Let me know whether the new version fixes the problem for you.

**Comment by raf10gh** [comment]
Working for me thanks for the quick fix.

**Comment by siku2** [comment]
Alright, closing this then
