### ISSUE TITLE
HA Core Beta 2024.1.0b3 breaks Weatherlink Integration

### ISSUE THREAD

**Issue by xpl01td** [siku2/hass-weatherlink#59]
HA Core Beta updates 2024.01.0b1 and above all break the Integration. Functions properly on 2023.12.4 .
See logs below:

Logger: homeassistant.setup
Source: setup.py:403
First occurred: 05:14:09 (3 occurrences)
Last logged: 05:20:12

Unable to prepare setup for platform 'weatherlink.sensor': Platform not found (Exception importing custom_components.weatherlink.sensor).
    
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 05:14:09 (3 occurrences)
Last logged: 05:20:12

Unexpected exception importing platform custom_components.weatherlink.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/weatherlink/sensor.py", line 4, in <module>
    from .sensor_air_quality import *
  File "/config/custom_components/weatherlink/sensor_air_quality.py", line 18, in <module>
    class AirQualitySensor(WeatherLinkSensor, abc=True):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in __new__
    return super().__new__(mcs, name, bases, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
  File "/config/custom_components/weatherlink/sensor_common.py", line 45, in __init_subclass__
    sensor_name = kwargs.pop("sensor_name")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'sensor_name'

**Comment by janssjay** [comment]
This is now in Production ...

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 1:24:40 PM (1 occurrences)
Last logged: 1:24:40 PM

Unexpected exception importing platform custom_components.weatherlink.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/weatherlink/sensor.py", line 4, in <module>
    from .sensor_air_quality import *
  File "/config/custom_components/weatherlink/sensor_air_quality.py", line 18, in <module>
    class AirQualitySensor(WeatherLinkSensor, abc=True):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in __new__
    return super().__new__(mcs, name, bases, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
  File "/config/custom_components/weatherlink/sensor_common.py", line 45, in __init_subclass__
    sensor_name = kwargs.pop("sensor_name")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'sensor_name'

**Comment by xpl01td** [comment]
Here are the logs from today's production release 2024.1.0 :

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 15:48:59 (1 occurrences)
Last logged: 15:48:59

Unexpected exception importing platform custom_components.weatherlink.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/weatherlink/sensor.py", line 4, in <module>
    from .sensor_air_quality import *
  File "/config/custom_components/weatherlink/sensor_air_quality.py", line 18, in <module>
    class AirQualitySensor(WeatherLinkSensor, abc=True):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in __new__
    return super().__new__(mcs, name, bases, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
  File "/config/custom_components/weatherlink/sensor_common.py", line 45, in __init_subclass__
    sensor_name = kwargs.pop("sensor_name")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'sensor_name'

**Comment by elji-lennart** [comment]
Same problem for me in 2024.1.0. Restore to 2023.12.3 is OK.

**Comment by stevebaggs** [comment]
Same here too, roll back to 2023.12.4 working OK.

**Comment by macoscar** [comment]
I have the same problem with 2024.1.0

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 11:22:49 (2 occurrences)
Last logged: 11:22:50

Unexpected exception importing platform custom_components.weatherlink.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/weatherlink/sensor.py", line 4, in <module>
    from .sensor_air_quality import *
  File "/config/custom_components/weatherlink/sensor_air_quality.py", line 18, in <module>
    class AirQualitySensor(WeatherLinkSensor, abc=True):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in __new__
    return super().__new__(mcs, name, bases, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
  File "/config/custom_components/weatherlink/sensor_common.py", line 45, in __init_subclass__
    sensor_name = kwargs.pop("sensor_name")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'sensor_name'

**Comment by ardyp87** [comment]
+1 having same issue after 2024.1.0 update

**Comment by vip-klaus** [comment]
Same here with the weatherlink-integration. Also same problem with the foxess_modbus-integration.

**Comment by NRutt2005** [comment]
I am having the issue below now, on 2024.1.0. I don't know if this is the same related issue as everyone else but everything worked fine until I updated to 2024.1.0. @siku2 

Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:194
Integration: Template (documentation, issues)
First occurred: 10:37:56 AM (31 occurrences)
Last logged: 10:46:52 AM

TemplateError('UndefinedError: 'None' has no attribute 'conditions'') while processing template 'Template<template=({{ state_attr("sensor.davis_vantage_pro_curr", "data")["conditions"][0]["temp"] }}) renders=28>' for attribute '_attr_native_value' in entity 'sensor.temp'
TemplateError('UndefinedError: 'None' has no attribute 'conditions'') while processing template 'Template<template=({{ state_attr("sensor.davis_vantage_pro_curr", "data")["conditions"][0]["hum"] }}) renders=28>' for attribute '_attr_native_value' in entity 'sensor.hum'
TemplateError('UndefinedError: 'None' has no attribute 'conditions'') while processing template 'Template<template=({{ state_attr("sensor.davis_vantage_pro_curr", "data")["conditions"][0]["wind_speed_last"] }}) renders=28>' for attribute '_attr_native_value' in entity 'sensor.wind_speed_template'
TemplateError('UndefinedError: 'None' has no attribute 'conditions'') while processing template 'Template<template=({{ state_attr("sensor.davis_vantage_pro_curr", "data")["conditions"][0]["wind_dir_last"] }}) renders=28>' for attribute '_attr_native_value' in entity 'sensor.wind_bearing_template'
TemplateError('UndefinedError: 'None' has no attribute 'conditions'') while processing template 'Template<template=({{ state_attr("sensor.davis_vantage_pro_curr", "data")["conditions"][0]["dew_point"] }}) renders=28>' for attribute '_attr_native_value' in entity 'sensor.dew_point_template'

**Comment by ornative** [comment]
Same Problem 2024.1 release:

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 3:42:31 PM (1 occurrences)
Last logged: 3:42:31 PM

Unexpected exception importing platform custom_components.weatherlink.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/weatherlink/sensor.py", line 4, in <module>
    from .sensor_air_quality import *
  File "/config/custom_components/weatherlink/sensor_air_quality.py", line 18, in <module>
    class AirQualitySensor(WeatherLinkSensor, abc=True):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in __new__
    return super().__new__(mcs, name, bases, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
  File "/config/custom_components/weatherlink/sensor_common.py", line 45, in __init_subclass__
    sensor_name = kwargs.pop("sensor_name")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'sensor_name'

**Comment by ppetru** [comment]
I think this is caused by home-assistant/core#107149 and have a fix that seems to work. Preparing a pull request.

**Comment by ppetru** [comment]
HA 2024.1.1 has been released with the fix.

**Comment by janssjay** [comment]
Confirmed!  HA 2024.1.1 resolved the issue for me.

**Comment by NRutt2005** [comment]
Confirmed as well! HA 2024.1.1 resolves this issue for me too.

**Comment by xpl01td** [comment]
2024.1.1 resolved for me as well.

**Comment by ornative** [comment]
Confirmed.  2024.1.1 resolved this.

**Comment by stevebaggs** [comment]
And here, all working in 2024.1.1

**Comment by GerhardKreuzer** [comment]
Hi,
just installed the integration, but get an error after entering the IP of the host.
Stopped the running Weatherlink software on my PC, same problems ...

How should I enter the 'Host name', I just know the IP address, need I some port? I am direc on the same network.

With best regards

Gerhard
